global:
  scrape_interval:     20s
  evaluation_interval: 10s

scrape_configs:
  - job_name: query_docker_stats
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['indexer_coordinator:8000']

  - job_name: query_count
    metrics_path: /metrics
    scheme: http
    bearer_token: rbLN2MUc7lLQq
    static_configs:
      - targets: ['indexer_proxy:8375']

  - job_name: node_exporter
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
