version: "3"

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  subquery_indexer:
    name: subquery_indexer
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET_MASK}/24
