version: "3"

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  subquery_indexer:
    name: subquery_indexer
    external: true

volumes:
    prometheus_data: {}
    grafana_data: {}

services:


  prometheus:
    image: prom/prometheus:latest
    container_name: indexer_prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./.data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.data/prometheus/prometheus.conf.d:/etc/prometheus/prometheus.conf.d
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      subquery_indexer:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.8
    expose:
      - 9090

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    expose:
      - 9100
    networks:
      subquery_indexer:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.9
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    restart: always

  grafana:
    image: grafana/grafana:10.0.3
    container_name: indexer_grafana
    networks:
      subquery_indexer:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.10
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./.data/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./.data/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=fifemon-graphql-datasource

  prometheus_graphql_exporter:
    image: ricardbejarano/graphql_exporter:latest
    container_name: prometheus_graphql_exporter
    networks:
      subquery_indexer:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.13
    expose:
      - 9199

  prometheus_bash_exporter:
    image: prometheus_bash_exporter:latest
    container_name: prometheus_bash_exporter
    restart: always
    command:
      - '/app/server'
      - '-debug=true'
      - '-labels=env,displayName,deploymentId'
    volumes:
      - ./src/docker/sh_exporter/scripts:/scripts
    networks:
      subquery_indexer:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.12
    build:
      context: ./src/docker/sh_exporter/
      dockerfile: Dockerfile
    expose:
      - 9300
