scrape_configs:
  - job_name: "graphql_exporter_QmPemHcmAJ6BRyV13FN91miLCHNtqXLLacsqYjSaTmbFmr"
    metrics_path: "/query"
    params:
      endpoint: ["http://indexer_coordinator:8000/graphql"]
      query:
        - |
          query {
            queryMetadata(id:"QmPemHcmAJ6BRyV13FN91miLCHNtqXLLacsqYjSaTmbFmr"){
              targetHeight
              lastProcessedHeight
              lastProcessedTimestamp
              specName
              chain
              indexerNodeVersion
              queryNodeVersion
              indexerStatus
              queryStatus
              __typename
            }
          }

    static_configs:
      - targets: ["prometheus_graphql_exporter:9199"]
      - labels:
          deploymentId: "QmPemHcmAJ6BRyV13FN91miLCHNtqXLLacsqYjSaTmbFmr"
          deploymentName: "Kusama Dictionary"
          
