scrape_configs:
  - job_name: "graphql_exporter_QmPHi8Y6bnLdidDjsd2sjgBdyEbwBu5s5QxN4n78zYpxJq"
    metrics_path: "/query"
    params:
      endpoint: ["http://indexer_coordinator:8000/graphql"]
      query:
        - |
          query {
            queryMetadata(id:"QmPHi8Y6bnLdidDjsd2sjgBdyEbwBu5s5QxN4n78zYpxJq"){
              targetHeight
              lastProcessedHeight
              lastProcessedTimestamp
              specName
              chain
              indexerNodeVersion
              queryNodeVersion
              indexerStatus
              queryStatus
              __typename
            }
          }

    static_configs:
      - targets: ["prometheus_graphql_exporter:9199"]
      - labels:
          deploymentId: "QmPHi8Y6bnLdidDjsd2sjgBdyEbwBu5s5QxN4n78zYpxJq"
          deploymentName: "Moonbeam Dictionary"
          
