scrape_configs:
  - job_name: "graphql_exporter_QmQtmsHoJEYUcxKE4tBqr9Z8kudcgkczQPfhkAxVExQX5y"
    metrics_path: "/query"
    params:
      endpoint: ["http://indexer_coordinator:8000/graphql"]
      query:
        - |
          query {
            queryMetadata(id:"QmQtmsHoJEYUcxKE4tBqr9Z8kudcgkczQPfhkAxVExQX5y"){
              targetHeight
              lastProcessedHeight
              lastProcessedTimestamp
              specName
              chain
              indexerNodeVersion
              queryNodeVersion
              indexerStatus
              queryStatus
              __typename
            }
          }

    static_configs:
      - targets: ["prometheus_graphql_exporter:9199"]
      - labels:
          deploymentId: "QmQtmsHoJEYUcxKE4tBqr9Z8kudcgkczQPfhkAxVExQX5y"
          deploymentName: "Nodle Parachain Dictionary"
          
