scrape_configs:
  - job_name: "graphql_exporter_QmSjjRjfjXXEfSUTheNwvWcBaH54pWoToTHPDsJRby955X"
    metrics_path: "/query"
    params:
      endpoint: ["http://indexer_coordinator:8000/graphql"]
      query:
        - |
          query {
            queryMetadata(id:"QmSjjRjfjXXEfSUTheNwvWcBaH54pWoToTHPDsJRby955X"){
              targetHeight
              lastProcessedHeight
              lastProcessedTimestamp
              specName
              chain
              indexerNodeVersion
              queryNodeVersion
              indexerStatus
              queryStatus
              __typename
            }
          }

    static_configs:
      - targets: ["prometheus_graphql_exporter:9199"]
      - labels:
          deploymentId: "QmSjjRjfjXXEfSUTheNwvWcBaH54pWoToTHPDsJRby955X"
          deploymentName: "Polkadot Dictionary"
          
