scrape_configs:
  - job_name: "graphql_exporter_QmUwTD5dqQRRFcMCihJ4HHnMPfEvRpKpcFvGcTJjBpGg9T"
    metrics_path: "/query"
    params:
      endpoint: ["http://indexer_coordinator:8000/graphql"]
      query:
        - |
          query {
            queryMetadata(id:"QmUwTD5dqQRRFcMCihJ4HHnMPfEvRpKpcFvGcTJjBpGg9T"){
              targetHeight
              lastProcessedHeight
              lastProcessedTimestamp
              specName
              chain
              indexerNodeVersion
              queryNodeVersion
              indexerStatus
              queryStatus
              __typename
            }
          }

    static_configs:
      - targets: ["prometheus_graphql_exporter:9199"]
      - labels:
          deploymentId: "QmUwTD5dqQRRFcMCihJ4HHnMPfEvRpKpcFvGcTJjBpGg9T"
          deploymentName: "Kepler Airdrop"
          
