scrape_configs:
  - job_name: "graphql_exporter_QmXCr6uZFdY1YcGTa4u6ZieQPXK4VHE1Pjy7CBr7ubFwKR"
    metrics_path: "/query"
    params:
      endpoint: ["http://indexer_coordinator:8000/graphql"]
      query:
        - |
          query {
            queryMetadata(id:"QmXCr6uZFdY1YcGTa4u6ZieQPXK4VHE1Pjy7CBr7ubFwKR"){
              targetHeight
              lastProcessedHeight
              lastProcessedTimestamp
              specName
              chain
              indexerNodeVersion
              queryNodeVersion
              indexerStatus
              queryStatus
              __typename
            }
          }

    static_configs:
      - targets: ["prometheus_graphql_exporter:9199"]
      - labels:
          deploymentId: "QmXCr6uZFdY1YcGTa4u6ZieQPXK4VHE1Pjy7CBr7ubFwKR"
          deploymentName: "Moonriver Dictionary"
          
