scrape_configs:
  - job_name: "graphql_exporter_QmYCAns2cunZKJFU85KNK8CvL2ATAmCFVZRdBf963GqWYs"
    metrics_path: "/query"
    params:
      endpoint: ["http://indexer_coordinator:8000/graphql"]
      query:
        - |
          query {
            queryMetadata(id:"QmYCAns2cunZKJFU85KNK8CvL2ATAmCFVZRdBf963GqWYs"){
              targetHeight
              lastProcessedHeight
              lastProcessedTimestamp
              specName
              chain
              indexerNodeVersion
              queryNodeVersion
              indexerStatus
              queryStatus
              __typename
            }
          }

    static_configs:
      - targets: ["prometheus_graphql_exporter:9199"]
      - labels:
          deploymentId: "QmYCAns2cunZKJFU85KNK8CvL2ATAmCFVZRdBf963GqWYs"
          deploymentName: "Khala Dictionary"
          
